---
title: "contigs-histograms"
author: "JP Flores"
date: "4/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading in the data
```{r}
library(readxl)
library(tidyverse)

tulipa_contigs <- read_excel("conuslab/TulipaTrimmedR.SPF.xlsx")

samoa_catus_contigs <- read_excel("conuslab/samoa_R_trimmed_contigs.SPF.xlsx")

purp_contigs <- read_excel("conuslab/PurpTrimmedRwContigs.SPF.xlsx")

hawaiian_catus_contigs <- read_excel("conuslab/hawaiian_R_trimmed_contigs.SPF.xlsx")

View(tulipa_contigs)
View(samoa_catus_contigs)
View(purp)
```

Cleaning the data
```{r}
tulipa_contigs <- tulipa_contigs %>% 
  rename("Contig" = `Table Data 3`)

tulipa_contigs <- tulipa_contigs %>% 
  mutate("Contig" = str_remove(tulipa_contigs$Contig,"Contig of"))

tulipa_contigs %>% 
  distinct(tulipa_contigs$Contig)

tulipa_contigs$Contig <- as.numeric(tulipa_contigs$Contig)

tulipa_contigs %>% 
    ggplot(aes(x = Contig)) +
  geom_histogram(binwidth = 1)
  
  
```

